[project]
name = "ng-pranker-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.8.*"
dependencies = [
    "websockets>=12.0",
    "aiohttp>=3.8.0",
    "aiohttp-cors>=0.7.0",
    "watchdog>=4.0.2",
    "loguru>=0.7.3",
]
