[project]
name = "ng-pranker-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.8.*"
dependencies = [
    "fastapi>=0.118.0",
    "opencv-python-headless>=4.12.0.88",
]
